export const sampleData = [
	{
		id: 1,
		name: "John Doe",
		age: 28,
		address: "123 Main St, Springfield, USA",
		phone: "555-1234",
		occupation: "Software Engineer",
		company: "Tech Solutions",
		salary: 70000,
		hireDate: "2020-01-15",
		department: "Engineering",
		status: "Active",
	},
	{
		id: 2,
		name: "Jane Smith",
		age: 34,
		address: "456 Elm St, Springfield, USA",
		phone: "555-5678",
		occupation: "Project Manager",
		company: "Tech Solutions",
		salary: 85000,
		hireDate: "2018-03-22",
		department: "Management",
		status: "Active",
	},
	{
		id: 3,
		name: "Alice Johnson",
		age: 29,
		address: "789 Oak St, Springfield, USA",
		phone: "555-8765",
		occupation: "UX Designer",
		company: "Creative Agency",
		salary: 65000,
		hireDate: "2019-07-30",
		department: "Design",
		status: "Active",
	},
	{
		id: 4,
		name: "Michael Brown",
		age: 40,
		address: "101 Pine St, Springfield, USA",
		phone: "555-6543",
		occupation: "Data Analyst",
		company: "Analytics Hub",
		salary: 72000,
		hireDate: "2021-02-10",
		department: "Data",
		status: "Active",
	},
	{
		id: 5,
		name: "Emily Davis",
		age: 25,
		address: "202 Cedar St, Springfield, USA",
		phone: "555-3210",
		occupation: "HR Specialist",
		company: "People Co.",
		salary: 54000,
		hireDate: "2019-11-25",
		department: "HR",
		status: "Active",
	},
	{
		id: 6,
		name: "Chris Wilson",
		age: 30,
		address: "303 Walnut St, Springfield, USA",
		phone: "555-7890",
		occupation: "Frontend Developer",
		company: "Web Studio",
		salary: 60000,
		hireDate: "2018-06-12",
		department: "Development",
		status: "Active",
	},
	{
		id: 7,
		name: "Sophia Garcia",
		age: 27,
		address: "404 Maple St, Springfield, USA",
		phone: "555-8901",
		occupation: "Marketing Specialist",
		company: "Ad Solutions",
		salary: 58000,
		hireDate: "2020-10-07",
		department: "Marketing",
		status: "Active",
	},
	{
		id: 8,
		name: "Daniel Martinez",
		age: 35,
		address: "505 Birch St, Springfield, USA",
		phone: "555-2345",
		occupation: "IT Consultant",
		company: "Tech Support",
		salary: 68000,
		hireDate: "2020-04-15",
		department: "IT",
		status: "Active",
	},
	{
		id: 9,
		name: "Isabella Rodriguez",
		age: 31,
		address: "606 Aspen St, Springfield, USA",
		phone: "555-5432",
		occupation: "Copywriter",
		company: "Creative Agency",
		salary: 52000,
		hireDate: "2021-08-01",
		department: "Content",
		status: "Active",
	},
	{
		id: 10,
		name: "James Lee",
		age: 38,
		address: "707 Cherry St, Springfield, USA",
		phone: "555-9876",
		occupation: "Business Analyst",
		company: "Biz Insights",
		salary: 77000,
		hireDate: "2017-03-14",
		department: "Analysis",
		status: "Active",
	},
	{
		id: 11,
		name: "Lucas Martin",
		age: 33,
		address: "808 Willow St, Springfield, USA",
		phone: "555-8760",
		occupation: "QA Tester",
		company: "Quality Matters",
		salary: 59000,
		hireDate: "2021-05-12",
		department: "Testing",
		status: "Active",
	},
	{
		id: 12,
		name: "Olivia Turner",
		age: 29,
		address: "909 Ash St, Springfield, USA",
		phone: "555-4321",
		occupation: "Graphic Designer",
		company: "Creative Agency",
		salary: 62000,
		hireDate: "2022-03-15",
		department: "Design",
		status: "Active",
	},
	{
		id: 13,
		name: "Benjamin Clark",
		age: 41,
		address: "111 Palm St, Springfield, USA",
		phone: "555-6789",
		occupation: "Operations Manager",
		company: "Operations Pro",
		salary: 87000,
		hireDate: "2016-07-18",
		department: "Operations",
		status: "Active",
	},
	{
		id: 14,
		name: "Charlotte Walker",
		age: 26,
		address: "222 Redwood St, Springfield, USA",
		phone: "555-1239",
		occupation: "SEO Specialist",
		company: "Online Optimizers",
		salary: 56000,
		hireDate: "2020-12-05",
		department: "Marketing",
		status: "Active",
	},
	{
		id: 15,
		name: "Henry White",
		age: 37,
		address: "333 Cypress St, Springfield, USA",
		phone: "555-3456",
		occupation: "Accountant",
		company: "Finance Matters",
		salary: 75000,
		hireDate: "2019-09-23",
		department: "Finance",
		status: "Active",
	},
	{
		id: 16,
		name: "Amelia Harris",
		age: 28,
		address: "444 Poplar St, Springfield, USA",
		phone: "555-5671",
		occupation: "Product Manager",
		company: "Innovations Inc.",
		salary: 80000,
		hireDate: "2021-04-10",
		department: "Product",
		status: "Active",
	},
	{
		id: 17,
		name: "Ethan Lewis",
		age: 45,
		address: "555 Hemlock St, Springfield, USA",
		phone: "555-8761",
		occupation: "Security Specialist",
		company: "Cyber Safe",
		salary: 82000,
		hireDate: "2015-01-19",
		department: "Security",
		status: "Active",
	},
	{
		id: 18,
		name: "Mia Scott",
		age: 32,
		address: "666 Fir St, Springfield, USA",
		phone: "555-7892",
		occupation: "Event Planner",
		company: "Eventful Days",
		salary: 61000,
		hireDate: "2019-11-29",
		department: "Events",
		status: "Active",
	},
	{
		id: 19,
		name: "Alexander King",
		age: 30,
		address: "777 Spruce St, Springfield, USA",
		phone: "555-5433",
		occupation: "Back-end Developer",
		company: "Web Studio",
		salary: 69000,
		hireDate: "2018-06-20",
		department: "Development",
		status: "Active",
	},
	{
		id: 20,
		name: "Lily Young",
		age: 36,
		address: "888 Sequoia St, Springfield, USA",
		phone: "555-0987",
		occupation: "Legal Consultant",
		company: "Legal Pro",
		salary: 93000,
		hireDate: "2017-08-22",
		department: "Legal",
		status: "Active",
	},
	{
		id: 21,
		name: "David Allen",
		age: 39,
		address: "999 Chestnut St, Springfield, USA",
		phone: "555-6548",
		occupation: "Support Technician",
		company: "HelpDesk Inc.",
		salary: 59000,
		hireDate: "2021-02-08",
		department: "Support",
		status: "Active",
	},
	{
		id: 22,
		name: "Ella Baker",
		age: 24,
		address: "1010 Beech St, Springfield, USA",
		phone: "555-1122",
		occupation: "Content Strategist",
		company: "Creative Agency",
		salary: 53000,
		hireDate: "2022-07-16",
		department: "Content",
		status: "Active",
	},
	{
		id: 23,
		name: "Matthew Robinson",
		age: 31,
		address: "1111 Magnolia St, Springfield, USA",
		phone: "555-3345",
		occupation: "Sales Representative",
		company: "SellSmart",
		salary: 62000,
		hireDate: "2018-02-14",
		department: "Sales",
		status: "Active",
	},
	{
		id: 24,
		name: "Zoe Mitchell",
		age: 27,
		address: "1212 Locust St, Springfield, USA",
		phone: "555-8876",
		occupation: "Technical Writer",
		company: "TechDocs",
		salary: 59000,
		hireDate: "2020-03-25",
		department: "Documentation",
		status: "Active",
	},
	{
		id: 25,
		name: "Ryan Clark",
		age: 43,
		address: "1313 Hawthorn St, Springfield, USA",
		phone: "555-7789",
		occupation: "Network Engineer",
		company: "NetSecure",
		salary: 91000,
		hireDate: "2016-10-12",
		department: "IT",
		status: "Active",
	},
	{
		id: 26,
		name: "Natalie Reed",
		age: 29,
		address: "1414 Cypress St, Springfield, USA",
		phone: "555-1134",
		occupation: "PR Coordinator",
		company: "Media Relations",
		salary: 57000,
		hireDate: "2019-05-18",
		department: "Public Relations",
		status: "Active",
	},
	{
		id: 27,
		name: "Nathan Torres",
		age: 38,
		address: "1515 Willow St, Springfield, USA",
		phone: "555-2256",
		occupation: "Inventory Manager",
		company: "Logistics Experts",
		salary: 67000,
		hireDate: "2017-09-21",
		department: "Inventory",
		status: "Active",
	},
	{
		id: 28,
		name: "Eva Perez",
		age: 34,
		address: "1616 Birch St, Springfield, USA",
		phone: "555-4478",
		occupation: "Training Specialist",
		company: "SkillSharp",
		salary: 65000,
		hireDate: "2018-11-30",
		department: "Training",
		status: "Active",
	},
	{
		id: 29,
		name: "Carter Hughes",
		age: 46,
		address: "1717 Maple St, Springfield, USA",
		phone: "555-5590",
		occupation: "Facilities Manager",
		company: "MaintainCo",
		salary: 78000,
		hireDate: "2015-05-10",
		department: "Facilities",
		status: "Active",
	},
	{
		id: 30,
		name: "Chloe Gray",
		age: 25,
		address: "1818 Aspen St, Springfield, USA",
		phone: "555-6672",
		occupation: "Social Media Coordinator",
		company: "Ad Solutions",
		salary: 52000,
		hireDate: "2022-09-05",
		department: "Social Media",
		status: "Active",
	},
];

// export const sampleData2 = [
//   {
//     "pjCd": "PJ001",
//     "buCd": "BU001",
//     "buName": "Business Unit 1",
//     "year": 2025,
//     "planSecCd": "PS001",
//     "planSecName": "Plan Section 1",
//     "constTypeCd": "CT001",
//     "constTypeName": "Construction Type 1",
//     "regionCd": "R001",
//     "regionName": "Region 1",
//     "pjName": "Project 1",
//     "customerCd": "C001",
//     "customerName": "Customer 1",
//     "abbreviation": "Abbr 1",
//     "order": "Order 1",
//     "startDate": "2025-01-01",
//     "totalMM": 12,
//     "totalConst": 1000,
//     "utilizationRate": {
//       "inhouse": 0.5,
//       "outsourced": 0.3,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 500,
//       "outsourced": 300,
//       "external": 200
//     },
//     "calculationBasis": "Calculation Basis 1",
//     "changeReason": "Change Reason 1",
//     "remarks": "Remarks 1"
//   },
//   {
//     "pjCd": "PJ002",
//     "buCd": "BU002",
//     "buName": "Business Unit 2",
//     "year": 2025,
//     "planSecCd": "PS002",
//     "planSecName": "Plan Section 2",
//     "constTypeCd": "CT002",
//     "constTypeName": "Construction Type 2",
//     "regionCd": "R002",
//     "regionName": "Region 2",
//     "pjName": "Project 2",
//     "customerCd": "C002",
//     "customerName": "Customer 2",
//     "abbreviation": "Abbr 2",
//     "order": "Order 2",
//     "startDate": "2025-02-01",
//     "totalMM": 13,
//     "totalConst": 1050,
//     "utilizationRate": {
//       "inhouse": 0.48,
//       "outsourced": 0.32,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 510,
//       "outsourced": 310,
//       "external": 205
//     },
//     "calculationBasis": "Calculation Basis 2",
//     "changeReason": "Change Reason 2",
//     "remarks": "Remarks 2"
//   },
//   {
//     "pjCd": "PJ003",
//     "buCd": "BU003",
//     "buName": "Business Unit 3",
//     "year": 2025,
//     "planSecCd": "PS003",
//     "planSecName": "Plan Section 3",
//     "constTypeCd": "CT003",
//     "constTypeName": "Construction Type 3",
//     "regionCd": "R003",
//     "regionName": "Region 3",
//     "pjName": "Project 3",
//     "customerCd": "C003",
//     "customerName": "Customer 3",
//     "abbreviation": "Abbr 3",
//     "order": "Order 3",
//     "startDate": "2025-03-01",
//     "totalMM": 14,
//     "totalConst": 1100,
//     "utilizationRate": {
//       "inhouse": 0.47,
//       "outsourced": 0.33,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 520,
//       "outsourced": 315,
//       "external": 210
//     },
//     "calculationBasis": "Calculation Basis 3",
//     "changeReason": "Change Reason 3",
//     "remarks": "Remarks 3"
//   },
//   {
//     "pjCd": "PJ004",
//     "buCd": "BU004",
//     "buName": "Business Unit 4",
//     "year": 2025,
//     "planSecCd": "PS004",
//     "planSecName": "Plan Section 4",
//     "constTypeCd": "CT004",
//     "constTypeName": "Construction Type 4",
//     "regionCd": "R004",
//     "regionName": "Region 4",
//     "pjName": "Project 4",
//     "customerCd": "C004",
//     "customerName": "Customer 4",
//     "abbreviation": "Abbr 4",
//     "order": "Order 4",
//     "startDate": "2025-04-01",
//     "totalMM": 15,
//     "totalConst": 1150,
//     "utilizationRate": {
//       "inhouse": 0.46,
//       "outsourced": 0.34,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 530,
//       "outsourced": 320,
//       "external": 215
//     },
//     "calculationBasis": "Calculation Basis 4",
//     "changeReason": "Change Reason 4",
//     "remarks": "Remarks 4"
//   },{
//     "pjCd": "PJ005",
//     "buCd": "BU005",
//     "buName": "Business Unit 5",
//     "year": 2025,
//     "planSecCd": "PS005",
//     "planSecName": "Plan Section 5",
//     "constTypeCd": "CT005",
//     "constTypeName": "Construction Type 5",
//     "regionCd": "R005",
//     "regionName": "Region 5",
//     "pjName": "Project 5",
//     "customerCd": "C005",
//     "customerName": "Customer 5",
//     "abbreviation": "Abbr 5",
//     "order": "Order 5",
//     "startDate": "2025-05-01",
//     "totalMM": 16,
//     "totalConst": 1200,
//     "utilizationRate": {
//       "inhouse": 0.45,
//       "outsourced": 0.35,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 540,
//       "outsourced": 325,
//       "external": 220
//     },
//     "calculationBasis": "Calculation Basis 5",
//     "changeReason": "Change Reason 5",
//     "remarks": "Remarks 5"
//   },
//   {
//     "pjCd": "PJ006",
//     "buCd": "BU006",
//     "buName": "Business Unit 6",
//     "year": 2025,
//     "planSecCd": "PS006",
//     "planSecName": "Plan Section 6",
//     "constTypeCd": "CT006",
//     "constTypeName": "Construction Type 6",
//     "regionCd": "R006",
//     "regionName": "Region 6",
//     "pjName": "Project 6",
//     "customerCd": "C006",
//     "customerName": "Customer 6",
//     "abbreviation": "Abbr 6",
//     "order": "Order 6",
//     "startDate": "2025-06-01",
//     "totalMM": 17,
//     "totalConst": 1250,
//     "utilizationRate": {
//       "inhouse": 0.44,
//       "outsourced": 0.36,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 550,
//       "outsourced": 330,
//       "external": 225
//     },
//     "calculationBasis": "Calculation Basis 6",
//     "changeReason": "Change Reason 6",
//     "remarks": "Remarks 6"
//   },
//   {
//     "pjCd": "PJ007",
//     "buCd": "BU007",
//     "buName": "Business Unit 7",
//     "year": 2025,
//     "planSecCd": "PS007",
//     "planSecName": "Plan Section 7",
//     "constTypeCd": "CT007",
//     "constTypeName": "Construction Type 7",
//     "regionCd": "R007",
//     "regionName": "Region 7",
//     "pjName": "Project 7",
//     "customerCd": "C007",
//     "customerName": "Customer 7",
//     "abbreviation": "Abbr 7",
//     "order": "Order 7",
//     "startDate": "2025-07-01",
//     "totalMM": 18,
//     "totalConst": 1300,
//     "utilizationRate": {
//       "inhouse": 0.43,
//       "outsourced": 0.37,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 560,
//       "outsourced": 335,
//       "external": 230
//     },
//     "calculationBasis": "Calculation Basis 7",
//     "changeReason": "Change Reason 7",
//     "remarks": "Remarks 7"
//   },
//   {
//     "pjCd": "PJ008",
//     "buCd": "BU008",
//     "buName": "Business Unit 8",
//     "year": 2025,
//     "planSecCd": "PS008",
//     "planSecName": "Plan Section 8",
//     "constTypeCd": "CT008",
//     "constTypeName": "Construction Type 8",
//     "regionCd": "R008",
//     "regionName": "Region 8",
//     "pjName": "Project 8",
//     "customerCd": "C008",
//     "customerName": "Customer 8",
//     "abbreviation": "Abbr 8",
//     "order": "Order 8",
//     "startDate": "2025-08-01",
//     "totalMM": 19,
//     "totalConst": 1350,
//     "utilizationRate": {
//       "inhouse": 0.42,
//       "outsourced": 0.38,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 570,
//       "outsourced": 340,
//       "external": 235
//     },
//     "calculationBasis": "Calculation Basis 8",
//     "changeReason": "Change Reason 8",
//     "remarks": "Remarks 8"
//   },{
//     "pjCd": "PJ009",
//     "buCd": "BU009",
//     "buName": "Business Unit 9",
//     "year": 2025,
//     "planSecCd": "PS009",
//     "planSecName": "Plan Section 9",
//     "constTypeCd": "CT009",
//     "constTypeName": "Construction Type 9",
//     "regionCd": "R009",
//     "regionName": "Region 9",
//     "pjName": "Project 9",
//     "customerCd": "C009",
//     "customerName": "Customer 9",
//     "abbreviation": "Abbr 9",
//     "order": "Order 9",
//     "startDate": "2025-09-01",
//     "totalMM": 20,
//     "totalConst": 1400,
//     "utilizationRate": {
//       "inhouse": 0.41,
//       "outsourced": 0.39,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 580,
//       "outsourced": 345,
//       "external": 240
//     },
//     "calculationBasis": "Calculation Basis 9",
//     "changeReason": "Change Reason 9",
//     "remarks": "Remarks 9"
//   },
//   {
//     "pjCd": "PJ010",
//     "buCd": "BU010",
//     "buName": "Business Unit 10",
//     "year": 2025,
//     "planSecCd": "PS010",
//     "planSecName": "Plan Section 10",
//     "constTypeCd": "CT010",
//     "constTypeName": "Construction Type 10",
//     "regionCd": "R010",
//     "regionName": "Region 10",
//     "pjName": "Project 10",
//     "customerCd": "C010",
//     "customerName": "Customer 10",
//     "abbreviation": "Abbr 10",
//     "order": "Order 10",
//     "startDate": "2025-10-01",
//     "totalMM": 21,
//     "totalConst": 1450,
//     "utilizationRate": {
//       "inhouse": 0.40,
//       "outsourced": 0.40,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 590,
//       "outsourced": 350,
//       "external": 245
//     },
//     "calculationBasis": "Calculation Basis 10",
//     "changeReason": "Change Reason 10",
//     "remarks": "Remarks 10"
//   },
//   {
//     "pjCd": "PJ011",
//     "buCd": "BU011",
//     "buName": "Business Unit 11",
//     "year": 2025,
//     "planSecCd": "PS011",
//     "planSecName": "Plan Section 11",
//     "constTypeCd": "CT011",
//     "constTypeName": "Construction Type 11",
//     "regionCd": "R011",
//     "regionName": "Region 11",
//     "pjName": "Project 11",
//     "customerCd": "C011",
//     "customerName": "Customer 11",
//     "abbreviation": "Abbr 11",
//     "order": "Order 11",
//     "startDate": "2025-11-01",
//     "totalMM": 22,
//     "totalConst": 1500,
//     "utilizationRate": {
//       "inhouse": 0.39,
//       "outsourced": 0.41,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 600,
//       "outsourced": 355,
//       "external": 250
//     },
//     "calculationBasis": "Calculation Basis 11",
//     "changeReason": "Change Reason 11",
//     "remarks": "Remarks 11"
//   },
//   {
//     "pjCd": "PJ012",
//     "buCd": "BU012",
//     "buName": "Business Unit 12",
//     "year": 2025,
//     "planSecCd": "PS012",
//     "planSecName": "Plan Section 12",
//     "constTypeCd": "CT012",
//     "constTypeName": "Construction Type 12",
//     "regionCd": "R012",
//     "regionName": "Region 12",
//     "pjName": "Project 12",
//     "customerCd": "C012",
//     "customerName": "Customer 12",
//     "abbreviation": "Abbr 12",
//     "order": "Order 12",
//     "startDate": "2025-12-01",
//     "totalMM": 23,
//     "totalConst": 1550,
//     "utilizationRate": {
//       "inhouse": 0.38,
//       "outsourced": 0.42,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 610,
//       "outsourced": 360,
//       "external": 255
//     },
//     "calculationBasis": "Calculation Basis 12",
//     "changeReason": "Change Reason 12",
//     "remarks": "Remarks 12"
//   },
//   {
//     "pjCd": "PJ013",
//     "buCd": "BU013",
//     "buName": "Business Unit 13",
//     "year": 2025,
//     "planSecCd": "PS013",
//     "planSecName": "Plan Section 13",
//     "constTypeCd": "CT013",
//     "constTypeName": "Construction Type 13",
//     "regionCd": "R013",
//     "regionName": "Region 13",
//     "pjName": "Project 13",
//     "customerCd": "C013",
//     "customerName": "Customer 13",
//     "abbreviation": "Abbr 13",
//     "order": "Order 13",
//     "startDate": "2026-01-01",
//     "totalMM": 24,
//     "totalConst": 1600,
//     "utilizationRate": {
//       "inhouse": 0.37,
//       "outsourced": 0.43,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 620,
//       "outsourced": 365,
//       "external": 260
//     },
//     "calculationBasis": "Calculation Basis 13",
//     "changeReason": "Change Reason 13",
//     "remarks": "Remarks 13"
//   },
//   {
//     "pjCd": "PJ014",
//     "buCd": "BU014",
//     "buName": "Business Unit 14",
//     "year": 2025,
//     "planSecCd": "PS014",
//     "planSecName": "Plan Section 14",
//     "constTypeCd": "CT014",
//     "constTypeName": "Construction Type 14",
//     "regionCd": "R014",
//     "regionName": "Region 14",
//     "pjName": "Project 14",
//     "customerCd": "C014",
//     "customerName": "Customer 14",
//     "abbreviation": "Abbr 14",
//     "order": "Order 14",
//     "startDate": "2026-02-01",
//     "totalMM": 25,
//     "totalConst": 1650,
//     "utilizationRate": {
//       "inhouse": 0.36,
//       "outsourced": 0.44,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 630,
//       "outsourced": 370,
//       "external": 265
//     },
//     "calculationBasis": "Calculation Basis 14",
//     "changeReason": "Change Reason 14",
//     "remarks": "Remarks 14"
//   },
//   {
//     "pjCd": "PJ015",
//     "buCd": "BU015",
//     "buName": "Business Unit 15",
//     "year": 2025,
//     "planSecCd": "PS015",
//     "planSecName": "Plan Section 15",
//     "constTypeCd": "CT015",
//     "constTypeName": "Construction Type 15",
//     "regionCd": "R015",
//     "regionName": "Region 15",
//     "pjName": "Project 15",
//     "customerCd": "C015",
//     "customerName": "Customer 15",
//     "abbreviation": "Abbr 15",
//     "order": "Order 15",
//     "startDate": "2026-03-01",
//     "totalMM": 26,
//     "totalConst": 1700,
//     "utilizationRate": {
//       "inhouse": 0.35,
//       "outsourced": 0.45,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 640,
//       "outsourced": 375,
//       "external": 270
//     },
//     "calculationBasis": "Calculation Basis 15",
//     "changeReason": "Change Reason 15",
//     "remarks": "Remarks 15"
//   },
//   {
//     "pjCd": "PJ016",
//     "buCd": "BU016",
//     "buName": "Business Unit 16",
//     "year": 2025,
//     "planSecCd": "PS016",
//     "planSecName": "Plan Section 16",
//     "constTypeCd": "CT016",
//     "constTypeName": "Construction Type 16",
//     "regionCd": "R016",
//     "regionName": "Region 16",
//     "pjName": "Project 16",
//     "customerCd": "C016",
//     "customerName": "Customer 16",
//     "abbreviation": "Abbr 16",
//     "order": "Order 16",
//     "startDate": "2026-04-01",
//     "totalMM": 27,
//     "totalConst": 1750,
//     "utilizationRate": {
//       "inhouse": 0.34,
//       "outsourced": 0.46,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 650,
//       "outsourced": 380,
//       "external": 275
//     },
//     "calculationBasis": "Calculation Basis 16",
//     "changeReason": "Change Reason 16",
//     "remarks": "Remarks 16"
//   },
//   {
//     "pjCd": "PJ017",
//     "buCd": "BU017",
//     "buName": "Business Unit 17",
//     "year": 2025,
//     "planSecCd": "PS017",
//     "planSecName": "Plan Section 17",
//     "constTypeCd": "CT017",
//     "constTypeName": "Construction Type 17",
//     "regionCd": "R017",
//     "regionName": "Region 17",
//     "pjName": "Project 17",
//     "customerCd": "C017",
//     "customerName": "Customer 17",
//     "abbreviation": "Abbr 17",
//     "order": "Order 17",
//     "startDate": "2026-05-01",
//     "totalMM": 28,
//     "totalConst": 1800,
//     "utilizationRate": {
//       "inhouse": 0.33,
//       "outsourced": 0.47,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 660,
//       "outsourced": 385,
//       "external": 280
//     },
//     "calculationBasis": "Calculation Basis 17",
//     "changeReason": "Change Reason 17",
//     "remarks": "Remarks 17"
//   },
//   {
//     "pjCd": "PJ018",
//     "buCd": "BU018",
//     "buName": "Business Unit 18",
//     "year": 2025,
//     "planSecCd": "PS018",
//     "planSecName": "Plan Section 18",
//     "constTypeCd": "CT018",
//     "constTypeName": "Construction Type 18",
//     "regionCd": "R018",
//     "regionName": "Region 18",
//     "pjName": "Project 18",
//     "customerCd": "C018",
//     "customerName": "Customer 18",
//     "abbreviation": "Abbr 18",
//     "order": "Order 18",
//     "startDate": "2026-06-01",
//     "totalMM": 29,
//     "totalConst": 1850,
//     "utilizationRate": {
//       "inhouse": 0.32,
//       "outsourced": 0.48,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 670,
//       "outsourced": 390,
//       "external": 285
//     },
//     "calculationBasis": "Calculation Basis 18",
//     "changeReason": "Change Reason 18",
//     "remarks": "Remarks 18"
//   },
//   {
//     "pjCd": "PJ019",
//     "buCd": "BU019",
//     "buName": "Business Unit 19",
//     "year": 2025,
//     "planSecCd": "PS019",
//     "planSecName": "Plan Section 19",
//     "constTypeCd": "CT019",
//     "constTypeName": "Construction Type 19",
//     "regionCd": "R019",
//     "regionName": "Region 19",
//     "pjName": "Project 19",
//     "customerCd": "C019",
//     "customerName": "Customer 19",
//     "abbreviation": "Abbr 19",
//     "order": "Order 19",
//     "startDate": "2026-07-01",
//     "totalMM": 30,
//     "totalConst": 1900,
//     "utilizationRate": {
//       "inhouse": 0.31,
//       "outsourced": 0.49,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 680,
//       "outsourced": 395,
//       "external": 290
//     },
//     "calculationBasis": "Calculation Basis 19",
//     "changeReason": "Change Reason 19",
//     "remarks": "Remarks 19"
//   },
//   {
//     "pjCd": "PJ020",
//     "buCd": "BU020",
//     "buName": "Business Unit 20",
//     "year": 2025,
//     "planSecCd": "PS020",
//     "planSecName": "Plan Section 20",
//     "constTypeCd": "CT020",
//     "constTypeName": "Construction Type 20",
//     "regionCd": "R020",
//     "regionName": "Region 20",
//     "pjName": "Project 20",
//     "customerCd": "C020",
//     "customerName": "Customer 20",
//     "abbreviation": "Abbr 20",
//     "order": "Order 20",
//     "startDate": "2026-08-01",
//     "totalMM": 31,
//     "totalConst": 1950,
//     "utilizationRate": {
//       "inhouse": 0.30,
//       "outsourced": 0.50,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 690,
//       "outsourced": 400,
//       "external": 295
//     },
//     "calculationBasis": "Calculation Basis 20",
//     "changeReason": "Change Reason 20",
//     "remarks": "Remarks 20"
//   },
//   {
//     "pjCd": "PJ021",
//     "buCd": "BU021",
//     "buName": "Business Unit 21",
//     "year": 2025,
//     "planSecCd": "PS021",
//     "planSecName": "Plan Section 21",
//     "constTypeCd": "CT021",
//     "constTypeName": "Construction Type 21",
//     "regionCd": "R021",
//     "regionName": "Region 21",
//     "pjName": "Project 21",
//     "customerCd": "C021",
//     "customerName": "Customer 21",
//     "abbreviation": "Abbr 21",
//     "order": "Order 21",
//     "startDate": "2026-09-01",
//     "totalMM": 32,
//     "totalConst": 2000,
//     "utilizationRate": {
//       "inhouse": 0.29,
//       "outsourced": 0.51,
//       "external": 0.2
//     },
//     "workHours": {
//       "inhouse": 700,
//       "outsourced": 405,
//       "external": 300
//     },
//     "calculationBasis": "Calculation Basis 21",
//     "changeReason": "Change Reason 21",
//     "remarks": "Remarks 21"
//   }
// ];
